### ISSUE TITLE
Error load plugin 

### ISSUE THREAD

**Issue by ghost** [webben-de/ASF_ItemDropper#11]
I droped latest release in folder "plugins" and asf giv me this error
![XAeALVP5zg](https://user-images.githubusercontent.com/31240253/123216917-3c143c80-d4f4-11eb-9870-fb092690cb9b.png)

**Comment by wollframium** [comment]
попробуй поставить нет.кор версию асф у меня все воркает.

**Comment by Sniper677** [comment]
Issue confirmed. As plugin release v0.3.1.1 was compiled against latest code of ASF, it stop working with ASF 5.1.0.9. Now with latest ASF release 5.1.1.1 it is working again. So please update to latest version of ASF.
