### ISSUE TITLE
Hello World tf2 need help

### ISSUE THREAD

**Issue by wollframium** [webben-de/ASF_ItemDropper#12]
Good afternoon, when drop tf2 will work?. I have succeeded in Payday2 Unturned, perhaps I would have had Keeling Floor 2 and I would have tried my luck there. but tf2 does not come out in any way.

**Comment by wollframium** [comment]
?

**Comment by Sniper677** [comment]
TF2 drop mechanic was changed in the past as far as I know. It only drops items in-game. Therefore the plugin will not work there.
It's not related to the plugin and cannot be fixed here.

**Comment by Sniper677** [comment]
Closed
