### ISSUE TITLE
formated console output for item drop

### ISSUE THREAD

**Issue by Sniper677** [webben-de/ASF_ItemDropper#3]
FILE: ItemDropHandler.cs

foreach (var item in QuickType.ItemList.FromJson(result.item_json))
                    {
                        summstring += $"Item dropped => ItemID: {appid}_{item.Itemid}, ItemDefinition: {item.Itemdefid} @ {item.StateChangedTimestamp}\n";
                    }

**Comment by webben-de** [comment]
done right? @Sniper677
