### ISSUE TITLE
In which games can I use this plugin?

### ISSUE THREAD

**Issue by FelipeBentoNG** [webben-de/ASF_ItemDropper#6]
Hello,

I would like to know in which games I can use this plugin to get drops.

If possible, please include an example command sequence that I have to type.

Sorry about the dumb question. I'm kinda confused

Thanks in advance!

**Comment by Sniper677** [comment]
The plugin works for any game which triggers item drops from client side. Known games to work are: Unturned, Killing Floor 2.
Example for games which do not work (anymore) Team Fortress 2.

Command examples:
`Unturned: idrop <botname> 304930 10000`
`KF2: idrop <botname> 232090 910000`

**Comment by wollframium** [comment]
Killing Floor 2
AppID: 232090
Drop List Definition: 910000

PAYDAY 2
AppID: 218620
Drop List Definition: 1

Rust
AppID: 252490
Drop List Definition: 10

Team Fortress 2
AppID: 440
Drop List Definition: 0

Unturned
AppID: 304930
Drop List Definition: 10000

Armello
AppID: 290340
Drop List Definition: 11
Items: Wyld Chest (55%), Wyld Key (45%)

Depth
AppID: 274940
Drop List Definition: 214
Items: Random Common (1/30)

Immune
AppID: 348670
Drop List Definition: 100
Items: Hat Case Venore (27%), Hat Case Fusion (27%), Hat Case Flags (27%), Skin Case One (18%)

Natural Selection 2
AppID: 4920
Drop List Definition: 700
Items: tradable, not marketable

Ratz Instagib 2.0
AppID: 338170
Drop List Definition: 10
Items: Common (56%), Rare (30%), Epic (12%), Legendary (2%)

Robot Roller-Derby Disco Dodgeball
AppID: 270450
Drop List Definition: 11

Savage Resurrection
AppID: 366440
Drop List Definition: 121

Zombie Grinder
AppID: 263920
Drop List Definition: 10

Call to Arms
AppID: 302670
Drop List Definition: 10

Intralism
AppID: 513510
Drop List Definition: 0

.atorb.
AppID: 467530
Drop List Definition: 10

**Comment by Sniper677** [comment]
Thanks for your feedback. Most games are unknown, at least to me.
You would need to test on your own if plugin works for them or not.
