### ISSUE TITLE
Can't use it on multiple bots at once

### ISSUE THREAD

**Issue by chuvak889** [webben-de/ASF_ItemDropper#9]
So, when i use !istart AFF <appid>, it says the appid is invalid, same goes for when i use !idrop.

It only works when i send the command to each bot in particular, and ONLY if i include the context ID aswell.

For example:
If i do it in private with each bot like this, it works:
!istart 218620 1
!idrop 218620 1

If i use !istart bot1,bot2,bot3 218620 1, it says the appID is invalid. Same if i just use ASF instead of listing each bot name (If i don't include the contextID it still gives the same error)

Is there any workaround?

**Comment by webben-de** [comment]
hey @Sniper677 can you answer that?

**Comment by Sniper677** [comment]
unfortunately this is the current status ... simply switching to .Net5 and recompile the current code does not work.
plugin can be loaded now with latest changes of webben-de, but giving errors like 'unknown command'.
we try to review our code ... for now I personally stick with older version and ASF v4.3.x.

**Comment by chuvak889** [comment]
I don't mind doing that (Older ASF with the older version of the plugin)
However, the invalid appID are in the older version aswell.

ASF 4.3.1.3
Item Dropper 0.1.0.0

Could you direct me towards the proper Item Dropper version, please?

Thanks a lot!

**Comment by Sniper677** [comment]
I am using ASF v4.3.1.0 with ASFItemDropper v0.1.0.0 form commit of 3rd November, which is this one:
https://github.com/Sniper677/ASF_ItemDropper/commit/4896c173ebae2aaf721fd855226f433d8b11c87d

Unfortunately the workflow artifacts expired. Therefore I add my saved ZIP from this date.
[ASF-ItemDropper.v0.1.0.0.zip](https://github.com/webben-de/ASF_ItemDropper/files/6076053/ASF-ItemDropper.v0.1.0.0.zip)

**Comment by chuvak889** [comment]
Thank you very much. I wish i could've helped you with this project but programming beats me. 

I used to do alot of stuff in VB6, but now my brain farts and freezes at even basic daily tasks. 

Oh well, thanks again, good luck  :)

**Comment by chuvak889** [comment]
One more question and i'll stop wasting your time, i still can't get the plugin to work on multiple bots at once, do i need ASF Generic or GenericTF? I am using WinX64.

**Comment by Sniper677** [comment]
use ASF-win-x64.zip in this case.

**Comment by chuvak889** [comment]
Hmm, then i don't know what i am doing wrong. It just says the appID is invalid when trying with multiple bots at once. Bummer.

I will check my configs, maybe it's something there, but i kinda doubt it.

**Comment by Sniper677** [comment]
last commit from yesterday fixes all currently known issues.
plugin is now running with ASF v5.x without problems for me.

**Comment by chuvak889** [comment]
Wow. Thanks alot. Works like charm
Amazing work!
